// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvs0i53JTfhcz7Cruj_TLeKTivuHRtQVQ',
    appId: '1:268154966103:web:abf4963d3e5678d629d312',
    messagingSenderId: '268154966103',
    projectId: 'beefit-3b937',
    authDomain: 'beefit-3b937.firebaseapp.com',
    storageBucket: 'beefit-3b937.appspot.com',
    measurementId: 'G-CE43XMWD04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-bcLZmDX03R-uh-p3jwA3j47My8BYQt4',
    appId: '1:268154966103:android:4a901900f8d5462f29d312',
    messagingSenderId: '268154966103',
    projectId: 'beefit-3b937',
    storageBucket: 'beefit-3b937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejLw1Fyk-6TdsN31ImDH9L2a_DtvvriY',
    appId: '1:268154966103:ios:bcadbc356d0094bb29d312',
    messagingSenderId: '268154966103',
    projectId: 'beefit-3b937',
    storageBucket: 'beefit-3b937.appspot.com',
    iosClientId: '268154966103-91loq3j3b5q156p1d63kehpo52lcbcgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.beeFit',
  );
}
